# Identificadores del proyecto
sonar.projectKey=Frontend-Dron
sonar.projectName=Frontend-Dron

# Código fuente
sonar.sources=src

# Ignorar archivos innecesarios
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/build/**

# Clave y conexión
sonar.host.url=http://localhost:9000
sonar.login="APIKEY"
